# Generated by Django 3.2.15 on 2023-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermelon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
