# Generated by Django 3.2.15 on 2023-05-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermelon', '0002_auto_20230501_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='survey_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
