# Generated by Django 3.2.15 on 2023-05-02 02:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('watermelon', '0003_alter_seller_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='survey_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
